language: node_js
node_js:
  - "8"

install: npm install
script: ./test.sh

cache:
  directories:
    - node_modules
    - docs/node_modules

notifications:
  webhooks:
    urls:
      - https://artipost.io/travis/hook
    on_start: always
