language: node_js
node_js:
  - "8"

install: npm install
script: ./test.sh

cache:
  directories:
    - node_modules
    - docs/node_modules

notifications:
  webhooks:
    urls:
      - http://srv01.apyos.com:4000/travis/hook
    on_start: always
