language: node_js
node_js:
  - "8"

install: npm install
script: npm test

cache:
  directories:
    - node_modules
    - docs/node_modules

notifications:
  webhooks:
    urls:
      - http://srv01.apyos.com:3000/travis
    on_start: always
